# Generated by Django 5.0.6 on 2024-07-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hh_cards", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hhcard",
            name="salary",
            field=models.FloatField(null=True),
        ),
    ]
